export type ChapterStatus =
  | "confirmed"
  | "pass"
  | "revise"
  | "fatal"
  | "unaudited"
  | "memory-pending";

export interface Chapter {
  id: string;
  index: number;
  title: string;
  outlineNodeId?: string | null;
  words: number;
  score: number | null;
  status: ChapterStatus;
  needsCheck?: boolean;
}

export interface Novel {
  id: string;
  title: string;
  genre: string;
  language?: string;
  coreIdea?: string;
  targetWords?: number;
  plannedChapters?: number;
  writingProfile?: WritingProfile;
  writingProfileReadiness?: WritingProfileReadiness;
  progress: { done: number; total: number };
  words: number;
  pendingAudits: number;
  updatedLabel: string;
  archived?: boolean;
}

export interface WritingProfile {
  ruleset?: string;
  strict_workflow: boolean;
  target_audience: string;
  platform: string;
  protagonist_name: string;
  protagonist_desire: string;
  protagonist_flaw: string;
  world_scale: string;
  power_system: string;
  golden_finger: string;
  golden_finger_cost: string;
  antagonist_mirror: string;
  anti_trope: string;
  hard_constraints: string[];
  anti_patterns: string[];
  learned_patterns: string[];
  bootstrap_status?: "" | "pending" | "running" | "complete" | "failed";
  bootstrap_stage?: "" | "blueprint" | "bible" | "volumes" | "arcs" | "chapters" | "complete";
  bootstrap_progress?: number;
  bootstrap_message?: string;
  bootstrap_error?: string;
  bootstrap_draft_source?: string;
  auto_generated?: boolean;
}

export interface NovelBootstrapStatus {
  novelId: string;
  status: "not_started" | "pending" | "running" | "complete" | "failed";
  stage: "blueprint" | "bible" | "volumes" | "arcs" | "chapters" | "complete";
  progress: number;
  message: string;
  error: string;
  autoGenerated: boolean;
  draftSource: string;
  blueprint: {
    bookTitle: string;
    logline: string;
    protagonistName: string;
    protagonistGoal: string;
    worldSetting: string;
  };
  counts: {
    characters: number;
    locations: number;
    factions: number;
    rules: number;
    volumes: number;
    arcs: number;
    chapters: number;
  };
  firstChapterId: string | null;
}

export interface WritingProfileReadiness {
  ready: boolean;
  missing: string[];
  strict: boolean;
  ruleset: string;
}

export interface AuditDimension {
  name: string;
  score: number;
  max: number;
}

export type IssueSeverity = "fatal" | "major" | "minor";

export interface AuditIssue {
  id: string;
  severity: IssueSeverity;
  type: string;
  evidence: string;
  evidenceQuote?: string;
  evidenceSource?: "content" | "outline" | "context";
  locatable?: boolean;
  ruleId?: string;
  blocking?: boolean;
  confidence?: number;
  location?: {
    source: "content" | "outline" | "context";
    start: number | null;
    end: number | null;
    quote: string;
  };
  conflictsWith: string;
  suggestion: string;
}

export type ParagraphKind = "normal" | "locked" | "audited";

export interface Paragraph {
  id: string;
  kind: ParagraphKind;
  text: string;
}

export type VersionSource = "user" | "generate" | "revise" | "rewrite" | "restore" | "confirm";

export interface ChapterVersion {
  id: string;
  label: string;
  source: VersionSource;
  model: string | null;
  score: number | null;
  time: string;
  words: number;
  current?: boolean;
  title?: string;
  content?: string;
  baseVersionId?: string | null;
  lockedRanges?: { start: number; end: number }[];
}

export interface CharacterSummary {
  id: string;
  name: string;
  role: string;
  status: string;
  locked?: boolean;
  summary?: string;
}

export interface LocationSummary {
  id: string;
  name: string;
  region: string;
  state: string;
  depth: number;
  summary?: string;
}

export interface FactionSummary {
  id: string;
  name: string;
  kind: string;
  stance: string;
  power: string;
  summary?: string;
}

export interface ItemSummary {
  id: string;
  name: string;
  kind: string;
  owner: string;
  state: string;
  summary?: string;
}

export interface WorldRule {
  id: string;
  rule: string;
  type: string;
  importance: "高" | "中" | "低";
  since: string;
  locked: boolean;
  violations: number;
}

export type ThreadStatus = "planted" | "developing" | "ready" | "paid" | "abandoned";

export interface PlotThread {
  id: string;
  name: string;
  kind: string;
  status: ThreadStatus;
  planted: string;
  payoff: string;
  importance: "高" | "中" | "低";
  latest: string;
}

export interface TimelineEvent {
  id: string;
  storyTime: string;
  chapter: string;
  subjects: string;
  action: string;
  location: string;
  consequence: string;
}

export interface Twist {
  id: string;
  chapter: string;
  surface: string;
  reality: string;
  clues: string;
  characters: string;
  aftermath: string;
}

export interface HighlightItem {
  id: string;
  chapter: string;
  text: string;
}

export interface ModelConfig {
  id: string;
  name: string;
  provider: string;
  modelId: string;
  status: "connected" | "error" | "untested";
  roles: string[];
  latency: string;
  baseUrl?: string;
  apiKeyMasked?: string;
  temperature?: number;
  topP?: number;
  maxOutputTokens?: number;
  contextSize?: number;
  timeoutMs?: number;
  isDefault?: boolean;
  extraBody?: Record<string, unknown>;
  novelId?: string | null;
  scope?: "workspace" | "novel";
}

export interface OutlineNode {
  id: string;
  kind: "volume" | "arc" | "chapter" | "scene";
  title: string;
  children?: OutlineNode[];
  locked?: boolean;
  details?: Record<string, unknown>;
}
